version: "2"

services:
  github-backup:
    build: .
    image: ghcr.io/umputun/github-backup-docker:master
    container_name: "github-backup"
    hostname: "github-backup"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - GITHUB_USER
      - TOKEN=${GITHUB_ACCESS_TOKEN}
      - MAX_BACKUPS=10
      - TIME_ZONE=America/Chicago
    volumes:
      - ./var:/srv/var
