version: "3"

services:
  github-backup:
    build: .
    image: umputun/github-backup:latest
    container_name: "github-backup"
    hostname: "github-backup"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - GITHUB_USER
      - TOKEN=${GITHUB_ACCESS_TOKEN}
      - TIME_ZONE
      - SLEEP
      - ARGS
    volumes:
      - ./var:/srv/var
